### ISSUE TITLE
any updates on this?

### ISSUE THREAD

**Issue by erfanoabdi** [MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel#1]
Hey @charleseb 
any news on releasing this techpack?
requesting for tag MMI-PPOS29.114-16-5-2 river

river, ocean and channel (all 4.9 msm8953s) need this audio driver for kernel

related issue: https://github.com/MotorolaMobilityLLC/kernel-msm/issues/235

thanks

**Comment by erfanoabdi** [comment]
https://github.com/MotorolaMobilityLLC/motorola-kernel-modules/blob/pie-9.0.0-release-ppo/sound/soc/codecs/Kbuild#L5

**Comment by charleseb** [comment]
Hi @erfanoabdi,

Sorry about the delay. I'm working on it. It will be available by next week.

Thanks,
Charles

**Comment by erfanoabdi** [comment]
Thanks for your reply;)

**Comment by wh0dat** [comment]
yea, and a INSTANT reply too.. seems I'm not worthy of ANY reply at all in a whole month ;(

**Comment by erfanoabdi** [comment]
thanks
