### ISSUE TITLE
Audio Problems with chef on Custom Roms.

### ISSUE THREAD

**Issue by Hasaber8** [MotorolaMobilityLLC/vendor-qcom-opensource-audio-kernel#2]
Hey @charleseb, we just can't get headphones working incall on chef on custom rom(pie) , after a lot of debugging it seems like kernel has some drivers and modules Missing on audio side for chef. If you could chef if any audio kernel stuff is left to released for chef and release it so we can fix the issue, it will be very nice is you. Also kernel release is pending for 9-PPTS29.74-41-5-8-9a9d1-release-keys.

**Comment by awheeler-mmi** [comment]
Hey @Hasaber8 , could you give us the filenames of the missing drivers/modules?  That would help us track down the problem.

Thanks,

-andrew

**Comment by Hasaber8** [comment]
> Hey @Hasaber8 , could you give us the filenames of the missing drivers/modules? That would help us track down the problem.
> 
> Thanks,
> 
> -andrew

As far as I can tell, it's seems to be an audio module, which does the work of handling incall headphone audio.

-Rohan

**Comment by Hasaber8** [comment]
> Hey @Hasaber8 , could you give us the filenames of the missing drivers/modules? That would help us track down the problem.
> 
> Thanks,
> 
> -andrew

So, in android ecosystem, we call 2 rings headphone(https://developer.android.com/reference/android/media/AudioDeviceInfo.html#TYPE_WIRED_HEADPHONES) and 3 ring headset(https://developer.android.com/reference/android/media/AudioDeviceInfo.html#TYPE_WIRED_HEADSET)
After more testing today on custom rom chef is messing up the 3 rings headset paths incall, but 2 rings headphones paths are just fine incall. It seems like you have made some changes in audio Hal's/kernel to avoid this in stock, but we cant find a way to fix this on custom rom, if you could shed some light on this topic it will be very nice!

-Rohan

**Comment by Hasaber8** [comment]
> Hey @Hasaber8 , could you give us the filenames of the missing drivers/modules? That would help us track down the problem.
> 
> Thanks,
> 
> -andrew

Any updates?
